### ISSUE TITLE
Need to credit author of Ascii.png tile set

### ISSUE THREAD

**Issue by softmoth** [mwbryant/monster-fighter#1]
The CP437 tile set being used as `Ascii.png` is from the Dwarf Fortress community. Probably the best link to credit its author is to [the Tileset repository](https://dwarffortresswiki.org/Tileset_repository#9.C3.979) wiki page.

This one happens to be the first 9x9 tileset listed, Author: Dorten, from 2009-02-13.

**Comment by mwbryant** [comment]
Thanks for the pointer, that appears to be the original author and I have added credit to the readme and will fix on all projects using this asset
