### ISSUE TITLE
Linux installation prerequisites

### ISSUE THREAD

**Issue by CrawfishPress** [mwbryant/monster-fighter#2]
Hello, I want to say thanks for this code (and the associated videos).

I did have an issue installing it, however, getting this error on cargo-build:
>   note: /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes

I have found references to `libxcb1-dev`, and `lxcb-shape` on Ubuntu, but nothing exactly like that. Are there some additional (outside of Rust/Bevy) libraries that need to be installed? Thanks.

Ubuntu 20.04
cargo 1.61.0 (a028ae4 2022-04-29)

**Comment by mwbryant** [comment]
Hmm I haven't run into this and I use the same OS.  Bevy does list some linux dependencies which may solve your problem https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md

**Comment by CrawfishPress** [comment]
Thanks for the reply. I was fairly sure I had installed all of the Bevy pre-reqs, but just checked, by re-installing the Ubuntu ones, and they were up-to-date, so that's not it.

**Comment by mwbryant** [comment]
Hmm then I'm going to redirect you to the bevy official issues or discord.  I'm not quite qualified to help with this kind of issue.  I'm excited to hear the solution though to help others.  There appear to be no exotic dependencies in the toml that I can see

**Comment by CrawfishPress** [comment]
Well, the Discord server was useful - there was an old thread referencing the `lxcb-shape` library, which is a pre-req of: [bevy-egui](https://github.com/mvlabat/bevy_egui) (and apparently a dependency of `bevy-inspector-egui`).  

So installing the pre-reqs for it, worked. After that, your repo compiled fine. :)

`sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev`

I don't know if that's a "flaw" in the Rust ecosystem, or not, I am still very new at it. But it wasn't obvious that the listed deps, had yet other deps - one of which, Linux-libraries (external to Rust), as a dependency, that needed to be manually installed. Then again, this has come up in Python (which I'm more familiar with), that libs needed C-header files that `pip install` couldn't manage.

**Comment by mwbryant** [comment]
I'm glad you were able to solve it!  I'd definitely say it's a flaw in the rust ecosystem and it would nice if error messages could at least link you to install instructions.  But I'm not involved in that sphere so I don't know how practical it would be to catch linker errors and let libraries give you a message.
